package Formulario;

import Tabla.Tablas;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Prototype2B
 */
public class Registros extends javax.swing.JFrame {
CallableStatement ps;
    /**
     * Creates new form Registros
     */
    public Registros() {
        initComponents();
        mostrar();
        mostrart();
        mostrary();
        mostrarx();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IDC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        N = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NIT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CORREO = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        J1 = new javax.swing.JTable();
        btn_ingresar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtide = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdpi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtableempleados = new javax.swing.JTable();
        btn_insertar1 = new javax.swing.JButton();
        btn_modificar2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtidm = new javax.swing.JTextField();
        txtmenu = new javax.swing.JTextField();
        txtp = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Jtablamenu = new javax.swing.JTable();
        bnt_insertar3 = new javax.swing.JButton();
        btn_mod3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtmesa = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        Jmenu = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        btn_ingresa4 = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID CLIENTE");

        jLabel2.setText("Nombre");

        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        jLabel4.setText("NIT");

        NIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NITActionPerformed(evt);
            }
        });

        jLabel5.setText("Correo");

        J1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        J1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                J1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(J1);

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ingresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btn_modificar))
                    .addComponent(IDC)
                    .addComponent(N)
                    .addComponent(A)
                    .addComponent(NIT)
                    .addComponent(CORREO, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(IDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CORREO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ingresar)
                    .addComponent(btn_modificar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CLIENTES", jPanel1);

        jLabel6.setText("ID EMPLEADO");

        jLabel7.setText("Nombre");

        jLabel8.setText("Apellido");

        jLabel9.setText("DPI");

        Jtableempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Jtableempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtableempleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Jtableempleados);

        btn_insertar1.setText("Ingresar");
        btn_insertar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertar1ActionPerformed(evt);
            }
        });

        btn_modificar2.setText("Modificar");
        btn_modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_insertar1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modificar2)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtide, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtdpi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtdpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertar1)
                    .addComponent(btn_modificar2))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EMPLEADOS", jPanel2);

        jLabel10.setText("ID MENU");

        jLabel12.setText("Nombre del MENU");

        jLabel13.setText("Precio");

        jLabel14.setText("Q");

        txtidm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidmActionPerformed(evt);
            }
        });

        Jtablamenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Jtablamenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtablamenuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Jtablamenu);

        bnt_insertar3.setText("Ingresar");
        bnt_insertar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_insertar3ActionPerformed(evt);
            }
        });

        btn_mod3.setText("Modificar");
        btn_mod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mod3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addGap(3, 3, 3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(61, 61, 61)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtidm, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bnt_insertar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btn_mod3))
                    .addComponent(txtmenu)
                    .addComponent(txtp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtidm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addComponent(txtmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_insertar3)
                    .addComponent(btn_mod3))
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("MENUS", jPanel3);

        jLabel15.setText("NUMERO DE MESA");

        Jmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane4.setViewportView(Jmenu);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 2, 36)); // NOI18N
        jLabel16.setText("RESTAURANTE NACIONAL");

        btn_ingresa4.setText("Ingresar");
        btn_ingresa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresa4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtmesa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_ingresa4)
                        .addGap(36, 36, 36)))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtmesa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_ingresa4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MESAS", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void mostrar(){
    Tablas p = new Tablas();
    J1.setModel(p.mostar());
    }
    
    public void mostrart(){
    Tablas p= new Tablas();
    Jtableempleados.setModel(p.mostar2());
    }
    
    public void mostrary(){
    Tablas p= new Tablas();
    Jtablamenu.setModel(p.mostar3());
    }
    public void mostrarx(){
    Tablas p= new Tablas();
    Jmenu.setModel(p.mostar4());
    }
    private void NITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NITActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
     try{
       Conexion cn = new Conexion();
       Connection conn= cn.getConection();
         int id= Integer.parseInt(IDC.getText());
            ps= (CallableStatement) conn.prepareCall("{Call INGRESAR (?,?,?,?,?)}");
            ps.setInt(1, id);
            ps.setString(2, N.getText());
            ps.setString(3, A.getText());
            ps.setString(4, NIT.getText());
            ps.setString(5, CORREO.getText());

            ps.execute();
            JOptionPane.showMessageDialog(null, "Dato ingresado");
            mostrar();
            IDC.setText("");
            N.setText("");
            A.setText("");
            NIT.setText("");
            CORREO.setText("");
            cn.CerrarConection();
        }catch(Exception e){
            System.err.println(e);
             
    }   
    
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
    try {
        Conexion cn = new Conexion();
        Connection conn= cn.getConection();
        int id= Integer.parseInt(IDC.getText());
        ps=conn.prepareCall("{Call MODIFICAR (?,?,?,?,?)}");
        ps.setString(1, N.getText());
        ps.setString(2, A.getText());
        ps.setString(3, NIT.getText());
        ps.setString(4,CORREO.getText());
        ps.setInt(5, id);
        int res = ps.executeUpdate();
        
        
        if(res>0){
            JOptionPane.showMessageDialog(null, "Dato modificado");
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No se pudo modificar");
        }
        mostrar();
        cn.CerrarConection();
    } catch (SQLException ex) {
        Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
    }
      
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void J1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J1MouseClicked
      seleccionar();
    }//GEN-LAST:event_J1MouseClicked

    private void btn_insertar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertar1ActionPerformed
      try{
       Conexion cn = new Conexion();
       Connection conn= cn.getConection();
       int id= Integer.parseInt(txtide.getText());
       
            ps= (CallableStatement) conn.prepareCall("{Call INGRESAR2 (?,?,?,?)}");
            ps.setInt(1, id);
            ps.setString(2, txtnombre.getText());
            ps.setString(3, txtap.getText());
            ps.setString(4, txtdpi.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Dato ingresado");
            mostrart();
            txtide.setText("");
            txtnombre.setText("");
            txtap.setText("");
            txtdpi.setText("");
           cn.CerrarConection();
        }catch(Exception e){
            System.err.println(e);
    }   
    }//GEN-LAST:event_btn_insertar1ActionPerformed

    private void btn_modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar2ActionPerformed
        try {
        Conexion cn = new Conexion();
        Connection conn= cn.getConection();
        int id= Integer.parseInt(txtide.getText());
        ps=conn.prepareCall("{Call MODIFICAR2 (?,?,?,?)}");
        
            ps.setString(1, txtnombre.getText());
            ps.setString(2, txtap.getText());
            ps.setString(3, txtdpi.getText());
            ps.setInt(4, id);
        int res = ps.executeUpdate();
        
        
        if(res>0){
            JOptionPane.showMessageDialog(null, "Dato modificado");
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No se pudo modificar");
        }
        mostrart();
        cn.CerrarConection();
    } catch (SQLException ex) {
        Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btn_modificar2ActionPerformed

    private void bnt_insertar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_insertar3ActionPerformed
        try{
       Conexion cn = new Conexion();
       Connection conn= cn.getConection();
       int id= Integer.parseInt(txtidm.getText());
            ps= (CallableStatement) conn.prepareCall("{Call INGRESAR3 (?,?,?)}");
            ps.setInt(1, id);
            ps.setString(2, txtmenu.getText());
            ps.setString(3, txtp.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Dato ingresado");
            mostrary();
            txtide.setText("");
            txtnombre.setText("");
            txtap.setText("");
            txtdpi.setText("");
            cn.CerrarConection();
        }catch(Exception e){
            System.err.println(e);
            
    }   
    }//GEN-LAST:event_bnt_insertar3ActionPerformed

    private void JtableempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtableempleadosMouseClicked
       seleccionar2();
    }//GEN-LAST:event_JtableempleadosMouseClicked

    private void txtidmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidmActionPerformed

    private void btn_mod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mod3ActionPerformed
       try {
        Conexion cn = new Conexion();
        Connection conn= cn.getConection();
        int id= Integer.parseInt(txtidm.getText());
        ps=conn.prepareCall("{Call MODIFICAR3 (?,?,?)}");
        ps.setString(1, txtmenu.getText());
            ps.setString(2, txtp.getText());
            ps.setInt(3, id);
        int res = ps.executeUpdate();
        
        
        if(res>0){
            JOptionPane.showMessageDialog(null, "Dato modificado");
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No se pudo modificar");
        }
        mostrary();
        cn.CerrarConection();
    } catch (SQLException ex) {
        Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btn_mod3ActionPerformed

    private void btn_ingresa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresa4ActionPerformed
      try{
       Conexion cn = new Conexion();
       Connection conn= cn.getConection();
            ps= (CallableStatement) conn.prepareCall("{Call INGRESAR4 (?)}");
            ps.setString(1, txtmesa.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Dato ingresado");
            mostrarx();
            txtide.setText("");
            txtnombre.setText("");
            txtap.setText("");
            txtdpi.setText("");
            cn.CerrarConection();
        }catch(Exception e){
            System.err.println(e);
    }   
    }//GEN-LAST:event_btn_ingresa4ActionPerformed

    private void JtablamenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtablamenuMouseClicked
       seleccionar3();
    }//GEN-LAST:event_JtablamenuMouseClicked
 
public void seleccionar(){
int select =J1.getSelectedRow();
IDC.setText((String)J1.getValueAt(select, 0));
N.setText((String)J1.getValueAt(select, 1));
A.setText((String)J1.getValueAt(select, 2));
NIT.setText((String)J1.getValueAt(select, 3));
CORREO.setText((String)J1.getValueAt(select, 4));
}

public void seleccionar3(){
int select =Jtablamenu.getSelectedRow();
txtidm.setText((String)Jtablamenu.getValueAt(select, 0));
txtmenu.setText((String)Jtablamenu.getValueAt(select, 1));
txtp.setText((String)Jtablamenu.getValueAt(select, 2));
}
public void seleccionar2(){
int select =Jtableempleados.getSelectedRow();
txtide.setText((String)Jtableempleados.getValueAt(select, 0));
txtnombre.setText((String)Jtableempleados.getValueAt(select, 1));
txtap.setText((String)Jtableempleados.getValueAt(select, 2));
txtdpi.setText((String)Jtableempleados.getValueAt(select, 3));
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField CORREO;
    private javax.swing.JTextField IDC;
    private javax.swing.JTable J1;
    private javax.swing.JTable Jmenu;
    private javax.swing.JTable Jtablamenu;
    private javax.swing.JTable Jtableempleados;
    private javax.swing.JTextField N;
    private javax.swing.JTextField NIT;
    private javax.swing.JButton bnt_insertar3;
    private javax.swing.JButton btn_ingresa4;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_insertar1;
    private javax.swing.JButton btn_mod3;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_modificar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtap;
    private javax.swing.JTextField txtdpi;
    private javax.swing.JTextField txtide;
    private javax.swing.JTextField txtidm;
    private javax.swing.JTextField txtmenu;
    private javax.swing.JTextField txtmesa;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtp;
    // End of variables declaration//GEN-END:variables
}
